### ISSUE TITLE
Compatibility Problem with ROS Noetic

### ISSUE THREAD

**Issue by altpebush6** [robustify/audibot#3]
I've tried to control it via turtlebot3_teleop and script but couldn't be successful. And also when I launch the project with single_vehicle_example.launch, the wheels doesn't located in the true location. What do you suggest about it?

![image](https://user-images.githubusercontent.com/93250409/158023076-534bfd08-9544-44cd-8a4c-a81cd817c793.png)

**Comment by altpebush6** [comment]
> I've tried to control it via turtlebot3_teleop and script but couldn't be successful. And also when I launch the project with single_vehicle_example.launch, the wheels doesn't located in the true location. What do you suggest about it?
> 
> ![image](https://user-images.githubusercontent.com/93250409/158023076-534bfd08-9544-44cd-8a4c-a81cd817c793.png)

I have ROS Noetic btw.

**Comment by robustify** [comment]
ROS Noetic was supported on the `noetic-devel` branch, but I just consolidated everything onto `master`. Therefore, the latest commit to `master` should work in both Melodic and Noetic now.

 You are still going to have issues controlling the vehicle with `turtlebot3_teleop` however. The most fundamental reason is because the simulator only supports raw throttle, brake, and steering wheel angle inputs and doesn't implement handling of a `geometry_msgs/Twist` message. I did this so that the simulator is as generic as possible, allowing people to implement their own controllers.

However, if you want to get up and running and just use a `geometry_msgs/Twist` message to control the vehicle, you can use the nodes in this repository as a starting point: [https://github.com/robustify/audibot_twist_controller](https://github.com/robustify/audibot_twist_controller)

**Comment by alalemp** [comment]
Not sure of the intent with tf's in the current update on main (the /tf and /tf_static)? 

The **audibot_named_robot.launch** seems to remap tf's onto (arg robot_name/tf).
This is followed by the new python **tf_prefix** node which attempts to republish the tf onto /tf.
What occurs is the tf_prefix republishes it adding the robot name again, so you get orange/orange/base_link for instance (with the two robots). 
Removing remapping and the then obsolete tf_prefixer and all is OK. I've tested this on 18.04 and 20.04

Maybe I'm missing  the intent behind publishing the tf under each robot namespace /orange/tf or /blue/tf?

**Comment by robustify** [comment]
@alalemp  Oops, I forgot to remove the `tf_prefix` parameter from `robot_state_publisher`, so both that and the custom `tf_prefixer.py` were each adding a TF prefix.

Thanks for pointing this out, and it made me realize that the devs finally merged in a re-implementation of the `tf_prefix` behavior back in September: https://github.com/ros/robot_state_publisher/pull/169. With that functionality re-implemented, `robot_state_publisher` works the same in both Melodic and Noetic, making the manual tf prefixing node unnecessary.

I removed everything to do with the custom tf prefixer node here: https://github.com/robustify/audibot/pull/4.
