### ISSUE TITLE
Missing xacro when launching example simulation

### ISSUE THREAD

**Issue by tl123987** [robustify/audibot#6]
![图片](https://github.com/robustify/audibot/assets/65206700/63805bc2-45cf-4b34-979d-262f7bcbee41)
Very strange

**Comment by robustify** [comment]
The problem is likely because `xacro` is not installed. You could just apt install `xacro`, but a more general tip is to use `rosdep`. The `xacro` package is listed as an `exec_depend` in the `audibot_description` package, so you can automatically install all missing dependencies like this:

```
rosdep update
rosdep install --from-paths src --ignore-src -r
```

Run the second command from the root folder of your ROS workspace. This works the same in ROS 1 and ROS 2.

**Comment by tl123987** [comment]
![图片](https://github.com/robustify/audibot/assets/65206700/5e8893c6-ffaa-425d-928a-d31a3a233e0b)
another problem happen

**Comment by robustify** [comment]
@tl123987  This is a separate problem from the original missing `xacro` issue. Please open a new issue with this problem.
